version: '17.2'

services:
  postgresql:
    image: postgres
    container_name: pg-bc
    ports:
      - "5436:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/bc-data 777
    environment:
      - 'POSTGRES_DB=book_catalog'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=admin'